image: docker:20.10.16-dind

services:
  - docker:dind

stages:
  - dependency
  - build
  - deploy

install_dependency:
  image: amazoncorretto:17-alpine-jdk
  stage: dependency
  script:
    - apk update
    - apk add npm
    - apk maven
    - npm --version
    - mvn --version
    - java --version

  only:
    - develop

build_job:
  image: amazoncorretto:17-alpine-jdk
  stage: build
  script:
    - cd frontend/
    - echo "Atualização de pacotes npm..."
    - npm install
    - echo "Iniciando Build do FrontEnd..."
    - npm run build
    - echo "Iniciando o build do BackEnd..."
    - mvn clean package -DskipTests

  artifacts:
    paths:
      - target/*.jar
  only:
    - develop

package_deploy_image:
  stage: deploy
  script:
    - echo "Criando a imagem Docker..."
    - docker build . -t "$DOCKERHUB_IMAGE_DEV"
    - echo "Mostrando lista de images..."
    - docker images
    - echo "Fazendo o deploy para o Docker Hub..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push "$DOCKERHUB_IMAGE_DEV"
  only:
    - develop
