image: docker:20.10.16-dind

services:
  - docker:dind

stages:
  - build
  - deploy

build_job:
  image: amazoncorretto:17-alpine-jdk
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar
  only:
    - develop

package_deploy_image:
  stage: deploy
  script:
    - echo "Criando a imagem Docker..."
    - docker build -t "$DOCKERHUB_IMAGE" .
    - echo "Mostrando lista de images..."
    - docker images
    - echo "Fazendo o deploy para o Docker Hub..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push "$DOCKERHUB_IMAGE"
  only:
    - develop
