image: docker:20.10.16-dind

services:
  - docker:dind

stages:
  - dependency-build
  - package-deploy

install_dependency-build:
  image: amazoncorretto:17-alpine-jdk
  stage: dependency-build
  script:
    - apk update
    - apk add npm 
    - apk add maven
    - cd frontend/
    - echo "Atualização de pacotes npm..."
    - npm install
    - echo "Iniciando Build do FrontEnd..."
    - npm run build
    - cd ../
    - echo "Iniciando o build do BackEnd..."
    - mvn clean package -DskipTests

  artifacts:
    paths:
      - target/*.jar
  only:
    - develop

package-deploy:
  stage: package-deploy
  script:
    - apk update
    - apk add --no-cache gettext curl
    - echo "Criando a imagem Docker..."
    - docker build . -t "$DOCKERHUB_IMAGE_DEV"
    - echo "Mostrando lista de images..."
    - docker images
    - echo "Fazendo o deploy para o Docker Hub..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push "$DOCKERHUB_IMAGE_DEV"
  # Deploy do kubernetes
    - echo "Instalando kubectl..."
    - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/am>
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p ~/.kube && echo "$KUBECONFIG_CONTENT" > ~/.kube/config  # Configura o KUBECONFIG
    - kubectl config use-context luiliomota/compara-imagens:kubecompara-dev
    - envsubst < compara-deployment.template.yaml > compara-deployment.yaml
    - kubectl apply -f compara-deployment.yaml
  only:
    - develop
