image: docker:20.10.16-dind

services:
  - docker:dind

stages:
  - build
  - deploy

build_job:
  image: openjdk:17-slim
  stage: build
  script:
    - apt-get update -y
    - apt-get install npm -y
    - apt-get install maven -y
    - mvn --version
    - java --version
    - npm --version
    - cd frontend/
    - pwd
    - npm install -y
    - npm run build -y
    - cd ../
    - pwd
    - echo "Iniciando o build..."
    - mvn clean package -DskipTests

  artifacts:
    paths:
      - target/*.jar
  only:
    - develop

package_deploy_image:
  stage: deploy
  script:
    - echo "Criando a imagem Docker..."
    - docker build . -t "$DOCKERHUB_IMAGE_DEV"
    - echo "Mostrando lista de images..."
    - docker images
    - echo "Fazendo o deploy para o Docker Hub..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push "$DOCKERHUB_IMAGE_DEV"
  only:
    - develop
