image: docker:20.10.16-dind

services:
  - docker:dind

stages:
  - build
  - deploy

build_job:
  image: openjdk:17.0.2-oracle
  stage: build
  script:
    - apt-get update
    - apt-get install maven
    - mvn --version
    - java --version
    - echo "Iniciando o build..."
    - mvn clean package -DskipTests

  artifacts:
    paths:
      - target/*.jar
  only:
    - develop

package_deploy_image:
  stage: deploy
  script:
    - echo "Criando a imagem Docker..."
    - docker build . -t "$DOCKERHUB_IMAGE_DEV"
    - echo "Mostrando lista de images..."
    - docker images
    - echo "Fazendo o deploy para o Docker Hub..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push "$DOCKERHUB_IMAGE_DEV"
  only:
    - develop
