apiVersion: apps/v1 # Kubernetes API version
kind: Deployment  # Kubernetes resource kind we are creating
metadata:
  name: compara-deployment
spec:
  selector:
    matchLabels:
      app: compara
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: compara
    spec:
      containers:
      - name: comparakube
        image: ${DOCKERHUB_IMAGE_PROD} # Image that will be used to containers in the cluster
        imagePullPolicy: Always
        env:
        - name: HOST_DB
          value: ${HOST_DB_PROD}
        - name: USERNAME_DB
          value: ${USERNAME_DB_PROD}
        - name: PASSWORD_DB
          value: ${PASSWORD_DB_PROD}
        ports:
        - containerPort: 8082 # The port that the container is running on in the cluster
---

kind: Service  # Kubernetes API version
apiVersion: v1 # Kubernetes resource kind we are creating
metadata:
  name: compara-service
spec:
  selector:
    app: compara
  ports:
  - protocol: TCP
    port: 8082   # The port that the service is running on in the cluster
    targetPort: 8082   # The port exposed by the service
    nodePort: 31000
  type: NodePort     # type of the service.
